### ISSUE TITLE
Governance contract issues

### ISSUE THREAD

**Issue by HabacucMX** [zenbitETH/Solarpunk-DAO#3]
- [x] 1. [Punk Cities contract](https://github.com/zenbitETH/Punk-Cities/blob/main/packages/hardhat/contracts/PunkCity.sol) is an ERC 1155 contract, verify compatibility on[ line 104 ](https://github.com/zenbitETH/Solarpunk-DAO/blob/c948a498630ffb1de70d9a870a267f6e7b936486/contracts/SolarPunkDAO.sol#L104)
- [x] 2. Energy and Chips are units from the ERC1155 contract, can still be deposited into the treasury?
- [x] 3. Deposits of energy and chips count as voting power?
- [x] 4. Can users deposit their place NFTs and count as voting power?
- [x] 5. Can we set conditionals to proposals and voting power to create them only on the deposited place NFTs?
- [x] #4

**Comment by Riki0923** [comment]
1. Working on it, I actually think that Haardik did not  code everything in the video, but I have changed the NFT contract now from ERC 721 to ERC 1155
2. Can they actually be TokenIds? And of course as they are ERC1155 we can add the amounts as well ( example: tokenID 1 should be energy, and lets say the amount is 100)
3. We can actually set the votingPower like the following: I deposit some energy to the DAO then I get one voting power
4. That can be as well
5. I think we can make such thing, let's say we create an array for each place NFT and the proposal will going to specify onl that place NFT
6. I need to double check this with you

**Comment by HabacucMX** [comment]
Lens network is not working to fetch post
